### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by weburnit** [weburnit/tippy#1]
/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
### Thank you for your Rails submission, weburnit!

:frowning: Unfortunately **there are some problems** with your submission:
- I couldn't find a Heroku deploy link listed in your `README.md`. Please note the URL where you have deployed your app.

**Comment by weburnit** [comment]
Humm... this codebase is applied for Swift Course! Fix me if I am wrong.
Regards.

**Comment by harley** [comment]
Hi @weburnit 

Thanks for the submissions. Indeed it's for the Swift course. Apologies for the wrong bot reply :)
We'll start reviewing Swift applications at the end of this week and into next week. You'll hear from us soon. Happy Tet! 

/cc @coderschoolreview

**Comment by coderschoolreview** [comment]
:+1: Nice job with the Tip Calculator.

### Some small comments:
- Good job with setting the currency.
- For now, there is no way to turn off the keyboard, so users cannot the the values in the segment.
  <img width="314" alt="screen shot 2016-02-20 at 10 31 30 pm" src="https://cloud.githubusercontent.com/assets/15702670/13197503/226e49b2-d822-11e5-9aef-fc1f0c338607.png">
- `Set the default percentage` feature means you have to set the default value for the segment, not as you did. In your app, it's a little bit weird when after users set `50%` as default and then they see the different selected value in the segment.

<img width="303" alt="screen shot 2016-02-20 at 10 32 44 pm" src="https://cloud.githubusercontent.com/assets/15702670/13197515/85cf6d9c-d822-11e5-80e7-8042e2bc2415.png">

Congratulation on completing the prework! The result will be emailed you next week.

**Comment by weburnit** [comment]
Big thanks @coderschoolreview ;)
I'll update soon within UnitTest
